workflows:
  ios_build_check:
    name: iOS Build Check (no signing)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Install pods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS (no codesign)
        script: flutter build ios --release --no-codesign

    artifacts:
      - /tmp/xcodebuild_logs/*.log
